### ISSUE TITLE
Handle deep linkings on redirect

### ISSUE THREAD

**Issue by daviddelucca** [nbiscan/deepLinkingExample#2]
Hey!

Do you know if is possible to handle a redirect with deep linking from server? I'm trying to implement it but the screen is opening and closing - the server returns a 302 but it's not working.

In my scenario, I have a authorize() functions that call my auth server and redirects it to "myapp://login" but login is opening and closing.

**Comment by nbiscan** [comment]
Hey David!

Thanks for reaching out.
It's definitely possible to handle a deep link that comes from your server
as a response. You'd just have to handle parsing that link and doing the
actual deep linking action on the front end.
What you're describing here doesn't look like a problem caused by deep link
from server but some other navigation issue. Would you mind sharing some
more details about your navigators (are you using bottom tab, stack, switch
ones?)

**Comment by daviddelucca** [comment]
Hey @nbiscan !

Thanks for the quick answer :)

Well, I'm not a react/mobile developer so I'm facing bad times against react-native and deep links 😞 

My scenario is super simple: I have a react native app that has a HomeScreen and a LoginScreen. My HomeScreen is the initial default screen and when it mounts, I run the function `authorize()`

I have figured out what was wrong: it was missing some configurations -.-

Thanks a lot for reply.
